### ISSUE TITLE
Flutter web support?

### ISSUE THREAD

**Issue by ciriousjoker** [julvo/flutter_page_slider#1]
Anytime soon? Maybe as a second branch?

In the meantime, here is my fork with the edited dependencies:
https://github.com/CiriousJoker/flutter_page_slider

**Comment by simongroom** [comment]
@CiriousJoker you have any knowledge on how to edit this such that it works on mobile AND web?? I tried using your fork, but flutter pub get kept failing on dependency/version issues..

`pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

Because every version of page_slider from git depends on flutter_web_ui any which is forbidden, page_slider from git is forbidden.

So, because myproject depends on page_slider from git, version solving failed.`

**Comment by ciriousjoker** [comment]
I haven't touched this in a really long time. I think Flutter Web is now integrated into Flutter Main, so maybe my fork became obsolete? Doesn't the normal plugin work out of the box with both Flutter Main & Flutter Web?

**Comment by simongroom** [comment]
Yes, my bad, I thought the error I was getting was due to flutter web support, but it was my implementation.. the normal plugin does indeed work with Flutter Web. Thanks.
